' =========================================================================
' IntyBASIC SDK Project: ponygame
' -------------------------------------------------------------------------
'     Programmer: [YOUR NAME]
'     Created:    05/29/2017
'     Updated:    05/29/2017
'
'     Project automatically generated by INTYNEW.
' -------------------------------------------------------------------------
' History:
' 05/29/2017 - ponygame project created.
' =========================================================================

	' Include useful predefined constants
	INCLUDE "constants.bas"

	' Remove the line below if you want to include your own custom title page.
	'INCLUDE "title.bas"

	'
        PRINT "PONY DEMO"
        WAIT
        DEFINE 0,3,ponysprites
        X=50
       
	'
        WAIT


InfiniteLoop:
        WAIT
        IF (X > 8) THEN X=X-1 ELSE X=160
        SPRITE 0,X + VISIBLE + ZOOMX2, 50 + ZOOMY2, SPR00+SPR_PINK + ((X/16 AND 1)*8) 
        SPRITE 1,X + VISIBLE + ZOOMX2, 50 + ZOOMY2, SPR02+SPR_RED
	GOTO InfiniteLoop

ponysprites:

REM 0

BITMAP "..#....."
BITMAP "###....."
BITMAP "###....."
BITMAP "..####.."
BITMAP "..####.."
BITMAP ".###.##."
BITMAP "#.#..#.#"
BITMAP "..#..#.."

REM 1

BITMAP "..#....."
BITMAP "###....."
BITMAP "###....."
BITMAP "..####.."
BITMAP "..####.."
BITMAP ".###.##."
BITMAP "..####.."
BITMAP "..#..#.."

REM 2

BITMAP ".#......"
BITMAP "...#...."
BITMAP "...#.##."
BITMAP "......##"
BITMAP "......##"
BITMAP ".......#"
BITMAP "........"
BITMAP "........"


